//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMark
    {
        public int SID { get; set; }
        public int SubjectID { get; set; }
        public string Term { get; set; }
        public double Mark { get; set; }
        public System.DateTime Year { get; set; }
    }
}
