//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string memberType { get; set; }
        public string accessLevel { get; set; }
        public string fullName { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string NIC { get; set; }
        public string DOB { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public string pastSchool { get; set; }
        public Nullable<int> serviceYears { get; set; }
        public string proPic { get; set; }
        public float salary { get; set; }
        public string password { get; set; }
        public string subject2 { get; set; }
    }
}
