//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int SID { get; set; }
        public string SNAME { get; set; }
        public string SEMAIL { get; set; }
        public string SADDRESS { get; set; }
        public Nullable<System.DateTime> SDOB { get; set; }
        public string SGENDER { get; set; }
        public string SGDNAME { get; set; }
        public string SGDCONTACT { get; set; }
        public string Grade { get; set; }
        public string ClassName { get; set; }
        public string SPASSWORD { get; set; }
    }
}
